version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: job-board-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 39lgzb2Kp6K9
      POSTGRES_DB: job_board
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job-board-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/job_board
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: ["npm", "start"]

volumes:
  pgdata:
